Update tectonic to 0.3.0
WtfJoke/tectonic-docker pull request #1
Opened 2020-11-02 20:46 UTC by PHPirates

Can you update the image on docker hub?

2020-11-04 18:50 UTC, WtfJoke commented
Woah, tectonic had some massive version bumps lately. 😮  Glad to see theres a release of tectonic with tflive2020. 

_/offtopic_
I've planned to switch to alpine images (so the docker image gets a bit smaller and debian stretch to buster increases the image size as well) and I even compiled biber 2.11 for linux musl, because tectonic wasnt using tflive2020 (and only compatible with biber 2.11) see https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.11/binaries/Linux-musl/
I'm planning to restructure this repo a bit to build multiple docker images with different tectonic versions (and tags), which gets uploaded automatically. So users can choose which version they want (or just stay with latest). 
_/offtopicend_

Thank you @PHPirates for taking care of this upgrade. 
Will test it shortly and then merge it

2020-11-04 19:34 UTC, WtfJoke commented
I experienced some errors during build. 

```
note: Running TeX ...
note: downloading article.cls
...
note: Writing `main.aux` (499 B)
note: Writing `main.bcf` (88.40 KiB)
note: Writing `main.run.xml` (2.29 KiB)
note: Writing `main.pdf` (4.75 KiB)
Removing intermediate container 1c4f0d554963
 ---> 590ebe7de170
Step 12/19 : RUN biber main
 ---> Running in a9098915b141
INFO - This is Biber 2.14
INFO - Logfile is 'main.blg'
INFO - Reading 'main.bcf'
ERROR - Error: Found biblatex control file version 3.4, expected version 3.7.
This means that your biber (2.14) and biblatex (3.11) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
The command '/bin/sh -c biber main' returned a non-zero code: 2
```
Any idea why tectonic 0.3.0 does not produce biber 2.14 compatible files?
```
$ docker run --rm -it 590ebe7de170
root@a1d75608da51:/usr/src/tex# tectonic --version
Tectonic 0.3.0
root@a1d75608da51:/usr/src/tex# biber --version
biber version: 2.14
```

2020-11-04 19:51 UTC, WtfJoke requested changes
See my last comment. Hope this works 😅

2020-11-04 19:51 UTC, WtfJoke commented on Dockerfile
> +RUN wget 'https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.14/binaries/Linux/biber-linux_x86_64.tar.gz'
```suggestion
RUN wget 'https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.11/binaries/Linux/biber-linux_x86_64.tar.gz'
```

Can you please change this back to biber 2.11 please

2020-11-04 19:51 UTC, WtfJoke commented on Dockerfile
> +RUN cargo install tectonic --force --vers 0.3.0
```suggestion
RUN cargo install tectonic --force --vers 0.3.1
```
tectonic 0.3.1 is out since a few days :)

2020-11-05 06:48 UTC, PHPirates commented
Oh yeah right, sorry. Because it doesn't use tl2020 as default, I had put this in my own dockerfile:

```
RUN mkdir -p ~/.config/Tectonic/
RUN echo "[[default_bundles]]" | tee --append ~/.config/Tectonic/config.toml
RUN echo "url = \"https://ttassets.z13.web.core.windows.net/tlextras-2020.0r0.tar\"" | tee --append ~/.config/Tectonic/config.toml
```
and that's where I tested it with.

You could consider releasing this also with a separate tag, but well I've already done that for myself so I'm happy anyway. Let's keep this PR for tl2018 then.


I did wonder why you used debian instead of alpine, but I thought you used debian because alpine didn't work for some reason... yeah different versions would be nice, perhaps like a 'latest' stable channel and a 'alpha/beta' testing channel so I don't have to manually update versions everywhere (which is tedious because I don't really like get a notification when you uploaded a new docker image)

2020-11-06 08:28 UTC, WtfJoke commented
Oh I see, the only problem I see now, that the docker images gets broken as soon as tectonic hits the switch to tllive2020. Maybe I should include it in this image as well (like you did)

> I did wonder why you used debian instead of alpine, but I thought you used debian because alpine didn't work for some reason...

Yeah, biber wasnt running on alpine. 🙈 


> yeah different versions would be nice, perhaps like a 'latest' stable channel and a 'alpha/beta' testing channel so I don't have to manually update versions everywhere (which is tedious because I don't really like get a notification when you uploaded a new docker image)

So far I was using different tags, for example: `dxjoke/tectonic-docker:0.1.12-biber` and `dxjoke/tectonic-docker:0.1.11-biber` and of course latest as well.
What would be the best way to share you new images? Probably we could automate it or at least agree on something.

2020-11-06 12:39 UTC, PHPirates commented
> Maybe I should include it in this image as well

Yeah, but it's a beta thing, so he might change it at any moment still, so that's why I would put it under a separate tag and not yet under latest. 

> What would be the best way to share you new images? 

If you keep the `latest` tag up to date it would be automatic I suppose. But if you automate releases to hub and I watch this repo for releases it would also work I guess.

2020-11-07 17:18 UTC, WtfJoke commented
LGTM

2020-11-07 17:18 UTC, merged

2020-11-07 18:00 UTC, WtfJoke commented
Pushed it to dockerhub under latest ;)